FROM alpine:3.12
MAINTAINER Daniel Schulz <danielschulz2005@hotmail.com>

LABEL SUSTAINABLE_CULTURE="https://sloanreview.mit.edu/culture500/" \
    CULTURE_EATS_STRATEGY="Unearthing the Roots of Corporate Social Irresponsibiity (https://www.zinio.com/de/reader/readsvg/447758/56)" \
    TEAM_GOALS="https://www.strategy-business.com/blog/Stretch-or-safe-The-art-of-setting-goals-for-your-teams?gko=4d547" \
    STRATEGIC_LEADERSHIP_PRINCIPLES="https://www.strategy-business.com/article/10-Principles-of-Strategic-Leadership" \
    LAZY_LEADERS_HEROIC_MANAGERS="https://www.strategy-business.com/article/Lazy-leaders-and-heroic-managers" \
    ROOTS_IRRESPONSIBLE_BEHAVIOUR="The Roots of Corporate Socail Irresponsible Behaviour is Unrealistic Performance Expectations, a Pressure-Cooker Culture and Stress (https://www.zinio.com/de/reader/readsvg/447758/56)"

RUN apk update && \
    apk add --no-cache nmap nmap-scripts nmap-nselibs curl wget bind-tools

CMD [ "sh" ]
