FROM alpine:3.12.3
MAINTAINER Daniel Schulz <danielschulz2005@hotmail.com>

LABEL SUSTAINABLE_CULTURE="https://sloanreview.mit.edu/culture500/" \
    CULTURE_EATS_STRATEGY="Unearthing the Roots of Corporate Social Irresponsibiity (https://www.zinio.com/de/reader/readsvg/447758/56)" \
    TEAM_GOALS="https://www.strategy-business.com/blog/Stretch-or-safe-The-art-of-setting-goals-for-your-teams?gko=4d547" \
    STRATEGIC_LEADERSHIP_PRINCIPLES="https://www.strategy-business.com/article/10-Principles-of-Strategic-Leadership" \
    SHY_AUTHENTIC_LEADERS="https://hbr.org/2020/12/why-capable-people-are-reluctant-to-lead" \
    EXHAUSTED_LEADERS="https://hbr.org/2020/12/how-to-lead-when-your-team-is-exhausted-and-you-are-too" \
    LAZY_LEADERS_HEROIC_MANAGERS="https://www.strategy-business.com/article/Lazy-leaders-and-heroic-managers" \
    ROOTS_IRRESPONSIBLE_BEHAVIOUR="The Roots of Corporate Socail Irresponsible Behaviour is Unrealistic Performance Expectations, a Pressure-Cooker Culture and Stress (https://www.zinio.com/de/reader/readsvg/447758/56)" \
    VISION="'We are stubborn on vision. We are flexible on details. We don’t give up on things easily.' (Jeff Bezos)" \
    AGILE_MANIFESTO="https://agilemanifesto.org" \
    SWE_MANIFESTO="https://manifesto.softwarecraftsmanship.org" \
    ROOTS_IRRESPONSIBLE_BEHAVIOUR="The Roots of Corporate Socail Irresponsible Behaviour is Unrealistic Performance Expectations, a Pressure-Cooker Culture and Stress (Rotman Magazine, Fall 2020, The Magazine of the Rotman School of Management, University of Toronto, https://www.zinio.com/de/reader/readsvg/447758/56)" \
    HBR_LEADING_BURNED_OUT="https://hbr.org/2020/12/how-to-lead-when-your-team-is-exhausted-and-you-are-too" \
    HBR_TRUST_CRISIS="https://hbr.org/2019/07/the-trust-crisis" \
    BCG_GETTING_MANAGERS_BACK_TO_WORK="https://www.bcg.com/de-de/publications/2018/bringing-managers-back-to-work" \
    MIT_HIDDEN_COSTS_DISHONESTY="https://sloanreview.mit.edu/article/the-hidden-costs-of-organizational-dishonesty/" \
    GOOGLE_RESEARCH_ML_IS_HIGHINTEREST_CREDIT_CARD="https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43146.pdf" \
    GOOGLE_HIDDEN_TECH_DEBT_IN_AI="https://papers.nips.cc/paper/2015/file/86df7dcfd896fcaf2674f757a2463eba-Paper.pdf" \
    AUTHOR_GITHUB="https://github.com/danielschulz" \
    AUTHOR_DOCKER_HUB="https://hub.docker.com/u/danielschulz" \
    AUTHOR_MEDIUM="https://medium.com/@danielschulz.it" \
    AUTHOR_WEBSITE="http://danielschulz.it" \
    AUTHOR_DATES="MjAxODEyMTMgMjAxODEyMTcgMjAxOTEwMTUgMjAyMDA4MjEgMjAyMDA5MjYK" \
    THOUGH_LEADERSHIP_FINANCE_BLOG="https://medium.com/wbaa" \
    DEAL_W_TECH_DEBT="https://medium.com/swlh/technical-air-pollution-the-reality-of-technical-debt-5afd96321f46" \
    BUILD_TIME_ALPINE="20201228_1445 UTC" \
    ONLY_DEAD_FISH_GO_W_FLOW="http://readingchomsky.blogspot.com/2014/07/noam-chomsky-2014-how-to-ruin-economy.html"

RUN apk update && \
    apk add --no-cache nmap nmap-scripts nmap-nselibs curl wget bind-tools bash curl wget socat

CMD [ "bash" ]
